vich_uploader:
    db_driver: orm

    mappings:
        pharmacies_images:
            uri_prefix: /images/pharmacies
            upload_destination: '%kernel.project_dir%/public/images/pharmacies'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
